import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { AppState } from 'store'
import { Status } from 'types'

export type Weather = {
  city: {
    id: number
    name: string
    coord: {
      lat: number
      lon: number
    }
    country: string
  }
  cnt: number
  cod: string
  list: {
    dt: number // date timestamp
    main: {
      temp: number
      temp_min: number
      temp_max: number
      pressure: number
      sea_level: number
      grnd_level: number
      humidity: number
      temp_kf: number
    }
    weather: {
      id: number
      main: string // Clear/Clouds/Rain
      description: string
      icon: string
    }[]
    clouds: {
      all: number
    }
    wind: {
      speed: number
      deg: number
    }
    sys: {
      pod: string
    }
    dt_txt: string // date in string
  }[]
  message: number
}

export type WeatherState = {
  status: Status
  data: Weather
  error: string | null | undefined
}

const initialState: WeatherState = {
  data: {} as Weather,
  status: Status.IDLE,
  error: null,
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchWeather(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchWeather = createAsyncThunk(
  'weather/fetchWeather',
  async (arg, { rejectWithValue }) => {
    try {
      const response = await fetch('/weather')
      const data = await response.json()

      if (!data || data?.errorMessage) {
        throw new Error('Data not found')
      }

      // The value we return becomes the `fulfilled` action payload
      return data
    } catch (error) {
      return rejectWithValue((error as Error).message)
    }
  }
)

export const weatherSlice = createSlice({
  name: 'weather',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchWeather.pending, (state) => {
        state.status = Status.PENDING
        state.error = null
      })
      .addCase(fetchWeather.fulfilled, (state, action) => {
        state.status = Status.FULFILLED
        state.data = action.payload
        state.error = null
      })
      .addCase(fetchWeather.rejected, (state, action) => {
        state.status = Status.REJECTED
        state.data = {} as Weather
        state.error = action.payload as string
      })
  },
})

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: AppState) => state.weather.value)`
export const selectWeather = (state: AppState) => state.weather

export default weatherSlice.reducer
